config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users

    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
      delete 'sign_out', to: 'devise/sessions#destroy'
    end

    get 'about', to: 'static_pages#about'
    get 'rules', to: 'static_pages#rules'
    get 'contacts', to: 'static_pages#contacts'

    root to: 'posts#index'

    scope module: :accounts do
      resources :accounts, shallow: true, except: %i[index show new create edit update destroy] do
        resources :friendships, only: %i[destroy]
        resources :messages, only: %i[new create]
        resources :conversations, only: %i[index show destroy]
        resources :invites, only: %i[create update]
      end
      resources :hobbies, only: %i[new create], as: 'account_hobbies'
    end

    scope module: :conversations do
      resources :conversations, shallow: true, except: %i[index show new create edit update destroy] do
        resources :messages, only: %i[create edit update destroy]
      end
    end

    shallow do
      resources :accounts do
        resources :friendships, only: %i[index destroy]
        resources :groups
      end
      resources :invites, except: %i[index show new create edit destroy] do
        resources :friendships, except: %i[index new show update destroy edit]
      end
      resources :posts do
        resources :comments, except: %i[show index]
      end
      resources :contents, except: %i[index show new create edit update destroy] do
        resources :comments, except: %i[show index]
      end
    end

    scope module: :groups do
      resources :groups, shallow: true, except: %i[index show new create edit update destroy] do
        resources :hobbies, except: %i[show index]
        resources :contents, except: %i[index]
      end
    end

    get 'account/:id/your_groups', to: 'groups#your_groups', as: 'your_groups'
    get 'account/:id/participation_groups', to: 'groups#participation_groups', as: 'participation_groups'
  end
end
# rubocop:enable Metrics/BlockLength

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  VALID_VISIBILITY = %w[everybody participants].freeze

  validates :name_group, presence: true, length: { within: 2..50 }
  validates :description, presence: true, length: { minimum: 2 }

  validates :visibility, inclusion: { in: VALID_VISIBILITY }

  has_many :group_participants, dependent: :destroy
  has_many :accounts, through: :group_participants

  has_many :group_hobbies, dependent: :destroy
  has_many :hobbies, through: :group_hobbies
  accepts_nested_attributes_for :hobbies, allow_destroy: true, update_only: true

  belongs_to :group_creator, class_name: 'Account', optional: true
  has_many :contents, dependent: :destroy

  has_one_attached :group_image
end

app/controllers/groups/contents_controller.rb
# frozen_string_literal: true

module Groups
  class ContentsController < ApplicationController
    before_action :authenticate_user!
    before_action :define_content!, except: %i[new create]
    before_action :define_group!, only: %i[new create]
    before_action :define_account!

    def show
      @group = @content.group
      @pagy_comment, @comments = pagy @content.comments.order_desc, items: 4, page_param: :pagy_comment
      @comments = @comments.decorate
    end

    def new
      @content = @group.contents.build
    end

    def edit; end

    def create
      @content = @group.contents.build content_params
      @content.account = @account
      if @content.save
        redirect_to content_path(@content),
                    success: I18n.t('flash.new', model: i18n_model_name(@content).downcase)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      return unless @account == @content.account

      if @content.update content_params
        redirect_to content_path(@content),
                    success: I18n.t('flash.update', model: i18n_model_name(@content).downcase)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      return unless @content.destroy

      redirect_to group_path(@group),
                  success: I18n.t('flash.destroy', model: i18n_model_name(@content).downcase)
    end

    private

    def define_content!
      @content = Content.find(params[:id]).decorate
    end

    def define_group!
      @group = Group.find params[:group_id]
    end

    def define_account!
      @account = Account.find_by user_id: current_user.id
    end

    def content_params
      params.require(:content).permit(:body, images: [])
    end
  end
end

app/controllers/groups/hobbies_controller.rb
# frozen_string_literal: true

module Groups
  class HobbiesController < ApplicationController
    before_action :authenticate_user!
    before_action :define_group!
    include HobbyAdd

    def new
      @hobby = Hobby.new
    end

    def create
      @hobby = Hobby.new_hobby hobby_params
      if @hobby.save
        hobby_add(@group, @hobby)
        return redirect_to group_path(@group),
                           success: I18n.t('flash.new', model: i18n_model_name(@hobby).downcase)
      end

      redirect_to group_path(@group),
                  danger: @hobby.errors.full_messages.each(&:capitalize).join(' ').to_s
    end

    private

    def define_group!
      @group = Group.find params[:group_id]
    end

    def hobby_params
      params.require(:hobby).permit(:hobby_name)
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :define_account!, except: %i[edit update destroy]
  before_action :define_group!, except: %i[index new create]

  def index
    @pagy, @all_groups = pagy Group.order(:name_group), items: 5
    @all_groups = @all_groups.decorate
  end

  def your_groups
    @pagy, @created_groups = pagy Group.where(group_creator: @account).order(:name_group), items: 5
    @created_groups = @created_groups.decorate
  end

  def participation_groups
    # @pagy, @participation_groups = pagy @account.groups.where.not(group_creator_id: @account.id), items: 5
    # @participation_groups = @participation_groups.decorate
  end

  def show
    @hobby = Hobby.new
    @pagy, @contents = pagy @group.contents.order(created_at: :desc), items: 5
    @contents = @contents.decorate
    @participants = @group.accounts
  end

  def new
    @group = @account.groups.build
    3.times { @group.hobbies.build }
  end

  def edit; end

  def create
    @group = @account.groups.build group_params
    if @group.save
      redirect_to group_path(@group),
                  success: I18n.t('flash.new', model: i18n_model_name(@group).downcase)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    return unless @group.group_creator == current_user.account

    if @group.update(group_params)
      redirect_to  group_path(@group),
                   success: I18n.t('flash.update', model: i18n_model_name(@group).downcase)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    return unless @group.group_creator == current_user.account
    return unless @group.destroy

    redirect_to account_groups_path(current_user.account),
                success: I18n.t('flash.destroy', model: i18n_model_name(@group).downcase)
  end

  private

  def define_account!
    @account = Account.find_by user_id: current_user.id
  end

  def define_group!
    @group = Group.find(params[:id]).decorate
  end

  def become_group_participant
    @account = Account.find_by user_id: current_user.id
    @group.accounts << @account unless @group.accounts.exists?(@account.id)
  end
  helper_method :become_group_participant

  def group_params
    params.require(:group).permit(:name_group, :description, :visibility,
                                  hobbies_attributes: %i[id hobby_name _destroy], 
                                  :group_image)
  end
end

app/helpers/group_helper.rb
# frozen_string_literal: true

module GroupHelper
  def group_page_name(page_name = '')
    render partial: 'navigation', locals: { page_name: page_name }
  end

  def link_nav(title, url, options = {})
    page_name = options.delete :page_name
    css_text = page_name == title ? 'btn btn-dark my-2 btn-sm' : 'btn btn-outline-dark my-2 btn-sm'
    options[:class] = if options[:class]
                        "#{options[:class]} #{css_text}"
                      else
                        css_text
                      end

    link_to title, url, options
  end
end

app/views/groups/_blank.html.erb
<section>
  <p><%= t('page.group.not_any_group') %></p>

  <%= link_to t('link.add_new', model: i18n_model_name(Group.new)), 
      new_account_group_path(@account), class: "btn btn-outline-dark btn-sm" %>
</section>

app/views/groups/_form.html.erb
<%= simple_form_for model, method: method do |f| %>
  <%#= f.file_field :avatar, class:"form-control", id: "formFile", input_html: { class: 'my-3'} %>
	<%= f.input :name_group, input_html: { class: 'mb-2'} %>
	<%= f.input :description, input_html: { class: 'mb-2' } %>
	<%= f.input :visibility, as: :radio_buttons, collection: Group::VALID_VISIBILITY, 
																								item_wrapper_class: 'inline',
																								input_html: { class: 'mx-2 mb-2' } %>

	<h4 class='mt-4 mb-2'><%= i18n_model_name(Hobby.new, count: 2) %></h4>
	<%= f.simple_fields_for :hobbies, include_id: false do |hobby_form| %>
		<%= hobby_form.input :hobby_name, input_html: { class: 'mb-2' } %>
	<% end %>

	<%= f.button :submit, f.object.new_record? ? t('submit.create', model: i18n_model_name(f.object).downcase) 
                                              : t('submit.edit', model: i18n_model_name(f.object).downcase), 
                                              class: "btn btn-outline-dark my-2 btn-sm" %>
	<%= render partial: 'shared/cancel_button', locals: { path: group_path(f.object) } if f.object.persisted? %>
<% end %>		

app/views/groups/_group.html.erb
 <article class="article">
  <h5 class='mt-4 mb-2'><%= link_to strip_tags(group.name_group), group_path(group) %></h5>
  <p class="infopost">
    <%= attribute_model(group, :author) %>
    <%= link_to group.group_creator.decorate.capitalize_name, account_path(group.group_creator) %>
    &nbsp;&bull;&nbsp;
    <span class="date">
      <time datetime="<%= group.created_at %>">
        <%= group.formatted_created_at %>
      </time>
    <span>
  </p>
  <div class="clr"></div>
  <div class="post_content">
    <p>
      <%= truncate strip_tags(group.description), length: 150, omission: '... (continued)' %>
    </p>
    <p class="spec" >
      <%= link_to sanitize(t('link.show_post')), group_path(group), class: "rm" %>
    </p>
  </div>
  <div class="clr"></div>
</article>

app/views/groups/_navigation.html.erb
<%= link_nav t('page.group.all_grops'), account_groups_path(@account), 
    role: 'button', page_name: page_name %>
<%= link_nav t('page.group.your_groups'), your_groups_path(@account), 
    page_name: page_name, role: 'button' %>
<%= link_nav t('page.group.participation_groups'), participation_groups_path(@account), 
    page_name: page_name, role: 'button' %>

app/views/groups/edit.html.erb
<section>
  <% provide :page_title, t('page.edit', model: i18n_model_name(@group).downcase) %>
  <% currently_at %>
  <h2 class='mt-4 mb-2'><%= t('page.edit', model: i18n_model_name(@group).downcase) %></h2>

  <%= render partial: 'form',  locals: { model: @group, method: :put, 
    submit: t('submit.edit', model: i18n_model_name(@group).downcase) } %>
</section>

app/views/groups/index.html.erb
<% provide :page_title, i18n_model_name(Group.new, count: 2) %>
<% currently_at i18n_model_name(Group.new, count: 2) %>
<%= group_page_name t('page.group.all_grops') %>

<article class='article'>
  <h2 class='mt-4 mb-2'><%= t('page.group.all_grops') %></h2>

  <% if @all_groups.try(:any?) %>
    <%= render @all_groups %>
    <div class='my-2'>
      <%== pagination(@pagy) %>
    </div>
  <% else %>
    <%= render 'blank' %>
  <% end %>
</artcile>

app/views/groups/new.html.erb
<section>
  <% provide :page_title, t('page.new', model: i18n_model_name(@group).downcase) %>
  <% currently_at %>

  <h2 class='mt-4 mb-2'><%= t('page.new', model: i18n_model_name(@group).downcase) %></h2>
  <%= render partial: 'shared/go_back_button', locals: { path: account_groups_path(@account) } %>

  <%= render partial: 'form',  locals: { model: [@account, @group], method: :post } %>
</section>

app/views/groups/participation_groups.html.erb
<% provide :page_title, i18n_model_name(Group.new, count: 2) %>
<% currently_at i18n_model_name(Group.new, count: 2) %>
<%= group_page_name t('page.group.participation_groups') %>

<article class='article'>
  <h2 class='mt-4 mb-2'><%= t('page.group.participation_groups') %></h2>

  <% if @created_groups.try(:any?) %>
    <%= render @participation_groups %>
    <div class='my-2'>
      <%== pagination(@pagy) %>
    </div>
  <% else %>
    <%= t('page.group.not_participants') %>
  <% end %>
</article>

app/views/groups/show.html.erb
<% provide :page_title, @group.name_group %>
<% currently_at %>

<article class="article profile">
  <h2 class='mt-4 mb-2'><%= @group.name_group %></h2>
  <div class='row row-cols-3'>
    <div class='col-1'>
      <% if @account == @group.group_creator %>
        <%= link_to(edit_group_path(@group), class: "btn btn-outline-dark btn-sm", 
            title:  t('link.edit', model: i18n_model_name(@group).downcase)) do %>
            <i class="bi bi-pencil-fill"></i>
        <% end %>
        <%= button_to(group_path(@group), method: :delete, :onclick => "return confirm('Are you sure?')", 
            :remote => true, class: "btn btn-outline-dark mt-1 btn-sm", 
            title: t('submit.delete', model: i18n_model_name(@group).downcase)) do %>
          <i class="bi bi-trash3-fill"></i>
        <% end %>
      <% end %>
    </div>
    <div class='col-8'>
      <p class="infopost">
        <%= attribute_model(@group, :creator) %>
        <%= link_to @group.group_creator.decorate.capitalize_name, account_path(@group.group_creator) %>
        &nbsp;&bull;&nbsp;
        <span class="date">
          <time datetime="<%= @group.created_at %>">
            <%= @group.formatted_created_at %>
          </time>
        <span>
      </p>
      <div class="clr"></div>
      <p>
        <strong><%= attribute_model(@group, :description) %>:&nbsp;</strong>
        <%= strip_tags @group.description %>
      </p>
      <div class="clr"></div>
      <% if @group.hobbies.try(:any?) %>
        <p>
          <strong><%= i18n_model_name(Hobby.new, count: 2) %>:&nbsp;</strong>
          <%= render @group.hobbies %>
        </p>
      <% end %>
      <p>
        <strong><%= attribute_model(@group, :visibility) %>:&nbsp;</strong>
        <%= @group.visibility %>
      </p>
    </div>
    <div class='col-3'>
      <h6><%= t('page.group.participations') %></h6>
        <%= button_to('#', method: :post, title: t('link.become_participant'), 
            class: "btn btn-outline-dark btn-sm profile my-1") do %>
          <%# become_group_participant %>
          <i class="bi bi-universal-access"></i>
        <% end %>
    </div>
  </div>
  <% if @account == @group.group_creator %>
    <%= turbo_frame_tag dom_id(@hobby) do %>
      <%= link_to(new_group_hobby_path(@group), class: "btn btn-outline-dark btn-sm mt-1", 
          title:  t('link.add_new', model: i18n_model_name(@hobby).downcase), ) do %>
        <i class="bi bi-scooter"></i>
      <% end %>
    <% end %>
  <% end %>
</article>
<section>
  <h3 class='mt-4 mb-2'><%= i18n_model_name(Content.new) %></h3>
  <% if @contents.try(:any?) %>
    <%= turbo_frame_tag dom_id(Content.new) do %>
      <%= link_to t('link.add_new_plural', model: attribute_model(Content.new, :body).downcase), 
          new_group_content_path(@group), class: "btn btn-outline-dark btn-sm mb-4" %>
    <% end %>
    <%= render partial: 'groups/contents/content', collection: @contents %>
  <% else %>
    <%= render 'groups/contents/empty_state' %>
  <% end%>
</section>

app/views/groups/your_groups.html.erb
<% provide :page_title, t('page.group.your_groups') %>
<% currently_at i18n_model_name(Group.new, count: 2) %>
<%= group_page_name t('page.group.your_groups') %>

<article class='article'>
  <h2 class='mt-4 mb-2'><%= t('page.group.your_groups') %></h2>
  
  <%= link_to t('link.add_new', model: i18n_model_name(Group.new)), 
      new_account_group_path(@account), class: "btn btn-outline-dark btn-sm" %>

  <% if @created_groups.try(:any?) %>
    <%= render @created_groups %>
    <div class='my-2'>
      <%== pagination(@pagy) %>
    </div>
  <% else %>
    <%= t('page.group.not_created') %>
  <% end %>
</article>