config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users

    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
      delete 'sign_out', to: 'devise/sessions#destroy'
    end

    get 'about', to: 'static_pages#about'
    get 'rules', to: 'static_pages#rules'
    get 'contacts', to: 'static_pages#contacts'

    root to: 'posts#index'

    scope module: :accounts do
      resources :accounts, shallow: true, except: %i[index show new create edit update destroy] do
        resources :friendships, only: %i[destroy]
        resources :messages, only: %i[new create]
        resources :conversations, only: %i[index show destroy]
        resources :invites, only: %i[create update]
      end
      resources :hobbies, only: %i[new create], as: 'account_hobbies'
    end

    scope module: :conversations do
      resources :conversations, shallow: true, except: %i[index show new create edit update destroy] do
        resources :messages, only: %i[create edit update destroy]
      end
    end

    shallow do
      resources :accounts do
        resources :friendships, only: %i[index destroy]
        resources :groups
      end
      resources :invites, except: %i[index show new create edit destroy] do
        resources :friendships, except: %i[index new show update destroy edit]
      end
      resources :posts do
        resources :comments, except: %i[show index]
      end
      resources :contents, except: %i[index show new create edit update destroy] do
        resources :comments, except: %i[show index]
      end
    end

    scope module: :groups do
      resources :groups, shallow: true, except: %i[index show new create edit update destroy] do
        resources :hobbies, except: %i[show index]
        resources :contents, except: %i[index]
      end
    end

    get 'account/:id/your_groups', to: 'groups#your_groups', as: 'your_groups'
    get 'account/:id/participation_groups', to: 'groups#participation_groups', as: 'participation_groups'
  end
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_cancel_button.html.erb
<%= link_to t("submit.cancel"), path, class: "btn btn-outline-dark btn-sm" %>

app/views/shared/_fbg.html.erb
<div class="fbg_resize">
  <div class="col c2">
    <h2><span><%= t('page.contacts.contacts') %></span></h2>
    <div itemscope itemtype="http://schema.org/Organization" class="contact_info">   
      <p>
        <span class='title'><%= t('page.contacts.company') %></span>&nbsp; 
        <span itemprop="name"><%= t('page.site_name') %></span>
      </p>
      <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress" class="contact_info">
        <p>
          <span class='title'><%= t('page.contacts.address.attr_address') %></span> &nbsp;
          <span itemprop="streetAddress"><%= t('page.contacts.address.address') %></span>
        </p>
        <p>
          <span class='title'><%= t('page.contacts.address.attr_post_code') %></span> &nbsp; 
          <span itemprop="postalCode"><%= t('page.contacts.address.post_code') %></span>
        </p>
        <p>
          <span class='title'><%= t('page.contacts.address.attr_city') %></span> &nbsp;
          <span itemprop="addressLocality"><%= t('page.contacts.address.city') %></span>
        </p>
      </div>
      <p>   
        <span class='title'><%= t('page.contacts.address.attr_phone') %></span> &nbsp;
        <span itemprop="telephone">
          <%= link_to t('page.contacts.address.phone'), "tel:#{t('page.contacts.address.phone')}" %>
        </span>
      </p>
      <p>
        <span class='title'><%= t('page.contacts.address.attr_email') %></span> &nbsp;
        <span itemprop="email">
          <%= link_to t('page.contacts.address.email'), "mailto: #{t('page.contacts.address.email')}" %>
        </span>
      </p>
      </div>
    </div>
    <div class="clr"></div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer_resize">
  <p class="lf">&copy;<%= t('page.site_name') %></p>
    <p class="rf">
      <%= link_to sanitize(t('page.telegram')), 'https://t.me/elenkasu', target: :_blank %>
    </p>        
  <div style="clear:both;"></div>
</footer>
 

app/views/shared/_go_back_button.html.erb
<%= link_to sanitize(t('submit.go_back')), path, class: "btn btn-outline-dark my-4 btn-sm", role: 'button' %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="header">
    <div class="header_resize">
      <div class="logo">
        <h1>
          <%= nav_tab t("page.site_name"), posts_path, current_page: current_page %>
          <small><%= t("page.slogan") %></small>
        </h1>
      </div>
      <div class="clr"></div>
      <nav class="menu_nav">
        <ul>
          <li>
            <span>
              <%= nav_tab t("navbar.about"), about_path, current_page: current_page %>
            </span>
          </li>
          <li>
            <span>
              <%= nav_tab t("navbar.rules"), rules_path,  current_page: current_page %>
            </span>
          </li>
          <li>
            <%= nav_tab t("navbar.contacts"), contacts_path, current_page: current_page %>
          </li>   
          <% if user_signed_in? %>
            <li>
              <%= button_to t('nav.sign_out'), sign_out_path, method: :delete, form: {turbolink: false}, 
                  :onclick => "return confirm('Are you sure?')", :remote => true %>
            </li>
          <% else %>
            <li class="dropdown">
              <%= link_to t('navbar.entrance'), '#', class: "dropdown-toggle", role: "button",
                'data-bs-toggle': "dropdown", 'aria-expanded': "false" %>
              <ul class='dropdown-menu'>
                <li>
                  <%= nav_tab t('nav.sign_in'), sign_in_path, class: "dropdown-item", current_page: current_page %>
                </li>
                <li><hr class='dropdown-divider'></li>
                <li>
                  <%= nav_tab t('nav.sign_up'), sign_up_path, class: "dropdown-item", current_page: current_page %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <div class="clr"></div>
<% end %>

app/views/shared/_right_menu.html.erb
<%= provide :right_menu do %>
  <nav class="gadget">
    <h2 class="star"><span><%= t('navbar.sidebar') %></span>&nbsp;<%= t('navbar.menu') %></h2>
    <div class="clr"></div>
    <ul class="sb_menu">
      <li>
        <%= nav_tab_right t('link.add_new', model: i18n_model_name(Account.new, count: 1).downcase), 
            new_account_path, current_page: current_page if current_user && !current_user.account.present? %>
      </li>
      <% if user_signed_in? && current_user.account.try(:present?) %> 
        <li>
          <%= nav_tab_right t("navbar.profile", user: current_user.account.user_name), 
              account_path(current_user.account), current_page: current_page %>
        </li>
        <li>
          <%= nav_tab_right i18n_model_name(Friendship.new, count: 2), 
              account_friendships_path(current_user.account), current_page: current_page %>
        </li>
        <li>
          <%= nav_tab_right i18n_model_name(Conversation.new, count: 2), 
              account_conversations_path(current_user.account), current_page: current_page %>
        </li>
      <li>
        <%= nav_tab_right i18n_model_name(Group.new, count: 2), account_groups_path(current_user.account), current_page: current_page %>
      </li>
      <% end %>
      <li>
        <%= nav_tab_right i18n_model_name(Post.new, count: 2), posts_path, current_page: current_page %>
      </li>
    </ul>
  </nav>
<% end %>