config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users

    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
      delete 'sign_out', to: 'devise/sessions#destroy'
    end

    get 'about', to: 'static_pages#about'
    get 'rules', to: 'static_pages#rules'
    get 'contacts', to: 'static_pages#contacts'

    root to: 'posts#index'

    scope module: :accounts do
      resources :accounts, shallow: true, except: %i[index show new create edit update destroy] do
        resources :friendships, only: %i[destroy]
        resources :messages, only: %i[new create]
        resources :conversations, only: %i[index show destroy]
        resources :invites, only: %i[create update]
      end
      resources :hobbies, only: %i[new create], as: 'account_hobbies'
    end

    scope module: :conversations do
      resources :conversations, shallow: true, except: %i[index show new create edit update destroy] do
        resources :messages, only: %i[create edit update destroy]
      end
    end

    shallow do
      resources :accounts do
        resources :friendships, only: %i[index destroy]
        resources :groups
      end
      resources :invites, except: %i[index show new create edit destroy] do
        resources :friendships, except: %i[index new show update destroy edit]
      end
      resources :posts do
        resources :comments, except: %i[show index]
      end
      resources :contents, except: %i[index show new create edit update destroy] do
        resources :comments, except: %i[show index]
      end
    end

    scope module: :groups do
      resources :groups, shallow: true, except: %i[index show new create edit update destroy] do
        resources :hobbies, except: %i[show index]
        resources :contents, except: %i[index]
      end
    end

    get 'account/:id/your_groups', to: 'groups#your_groups', as: 'your_groups'
    get 'account/:id/participation_groups', to: 'groups#participation_groups', as: 'participation_groups'
  end
end
# rubocop:enable Metrics/BlockLength

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :invite
  belongs_to :f_partner_friendship, class_name: 'Account', optional: true
  belongs_to :s_partner_friendship, class_name: 'Account', optional: true

  def self.user_friends(account)
    where(f_partner_friendship: account).or(Friendship.where(s_partner_friendship: account))
  end
end

app/controllers/accounts/friendships_controller.rb
# frozen_string_literal: true

module Accounts
  class FriendshipsController < ApplicationController
    include DeleteInvite
    before_action :authenticate_user!
    after_action :delete_invite

    def destroy
      @account = current_user.account
      @account = @account.decorate
      @friendship = Friendship.find params[:id]

      return unless @friendship.destroy

      @friendship.invite.destroy
      redirect_to account_path(@account),
                  success: I18n.t('flash.friend_canceled', username: @account.capitalize_name)
    end
  end
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  include InvitesHelper
  include FriendshipsHelper
  include DeleteInvite
  before_action :authenticate_user!
  before_action :define_account!
  before_action :delete_canceled_invites, only: %i[index]
  after_action :delete_invite, only: %i[destroy]

  def index
    @pagy_friend, @friends = pagy Friendship.user_friends(@sender), items: 10, page_param: :pagy_friend

    @pagy_sender, @invites_sender = pagy Invite.account_sender_invites(@sender), items: 7,
                                                                                 page_param: :pagy_sender
    @pagy_receiver, @invites_receiver = pagy Invite.account_receiver_invites(@sender), items: 7,
                                                                                       page_param: :pagy_receiver
  end

  def create
    @invite = Invite.find params[:invite_id]
    @sender = @invite.sender_invite
    @receiver = @invite.receiver_invite

    return if check_friendship? @sender, @receiver

    @friendship = @invite.build_friendship(f_partner_friendship: @sender, s_partner_friendship: @receiver)

    return unless @friendship.save

    @invite.update confirmed: 'yes'
    redirect_to account_friendships_path(@sender),
                success: I18n.t('flash.accept', model: i18n_model_name(@friendship).downcase)
  end

  def destroy
    @friendship = Friendship.find params[:id]

    return unless @friendship.destroy

    @friendship.invite.destroy
    redirect_to account_friendships_path(@sender),
                success: I18n.t('flash.friend_canceled', username: find_friend(@friendship).capitalize_name)
  end

  private

  def define_account!
    @sender = Account.find_by user_id: current_user.id
    @pagy_account, @accounts = pagy Account.except_current_account(@sender), items: 20, page_param: :pagy_account
    @accounts = @accounts.decorate
  end

  def delete_canceled_invites
    canceled_infites = Invite.where(confirmed: 'canceled')
    canceled_infites.destroy_all
  end

  def friendship_params
    params.require(:friendship).permit(:confirmed)
  end
end

app/helpers/friendships_helper.rb
# frozen_string_literal: true

module FriendshipsHelper
  def find_friendship(sender, recipient)
    Friendship.find_by(f_partner_friendship: sender, s_partner_friendship: recipient) ||
      Friendship.find_by(s_partner_friendship: sender, f_partner_friendship: recipient)
  end

  def check_friendship?(sender, recipient)
    return true if find_friendship(sender, recipient)
  end

  def find_friend(friendship)
    return friendship.s_partner_friendship.decorate if friendship.f_partner_friendship == current_user.account

    friendship.f_partner_friendship.decorate
  end
end

app/views/friendships/_delete_button.html.erb
<%= button_to(path, method: :delete, :onclick => "return confirm('Are you sure?')", 
    :remote => true, class: "btn btn-outline-dark mb-2 btn-sm profile", 
    title: t('submit.friend')) do %>
    <i class="bi bi-x-square-fill"></i>
<% end %>

app/views/friendships/_friendship.html.erb
<div class='row row-cols-2'>
  <div class='col'>
    <%= link_to find_friend(friendship).decorate.capitalize_name, account_path(find_friend(friendship)) %>
  </div>
  <div class='col'>
    <%= render partial: 'delete_button', locals: { path: friendship_path(friendship) } %>
  </div>
</div>

app/views/friendships/index.html.erb
<% provide :page_title, i18n_model_name(Friendship.new, count: 2) %>
<% currently_at i18n_model_name(Friendship.new, count: 2) %>

<article = class='article'>
  <div class='row row-cols-3'>
    <div class='col'>
      <h3 class='mt-4 mb-2'><%= i18n_model_name(Friendship.new, count: 2) %></h3>
      <div class="clr"></div>
      <% if @friends.try(:any?) %>
        <%= render @friends %>
        <div class='my-2'>
          <%== pagination(@pagy_friend) %>
        </div>
      <% else %>
        <p><%= t('page.friendship.blank') %></p>
      <% end %>
    </div>
    <div class='col'>
      <h3 class='mt-4 mb-2'> <%= i18n_model_name(Invite.new, count: 2) %></h3>
      <% if @invites_sender.try(:any?) %>
        <p><strong><%= t('page.invite.your_invite.you_are_sender') %></strong></p>
          <%= render @invites_sender %>
          <div class='my-2'>
            <%== pagination(@pagy_sender) %>
          </div>
      <% end %>
      <% if @invites_receiver.try(:any?) %>
        <p><strong><%= t('page.invite.users_invite.sender') %></strong></p>
        <%= render @invites_receiver %>
        <div class='my-2'>
          <%== pagination(@pagy_receiver) %>
        </div>      
      <% end %>
    </div>
    <div class='col'>
      <h3 class='mt-4 mb-2'><%= t('page.friendship.accounts') %></h3>
      <% if @accounts.any? %>
        <%= render @accounts %>
        <div class='my-2'>
          <%== pagination(@pagy_account) %>
        </div> 
      <% end %>
    </div>
  </div>
</article>