config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users

    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
      delete 'sign_out', to: 'devise/sessions#destroy'
    end

    get 'about', to: 'static_pages#about'
    get 'rules', to: 'static_pages#rules'
    get 'contacts', to: 'static_pages#contacts'

    root to: 'posts#index'

    scope module: :accounts do
      resources :accounts, shallow: true, except: %i[index show new create edit update destroy] do
        resources :friendships, only: %i[destroy]
        resources :messages, only: %i[new create]
        resources :conversations, only: %i[index show destroy]
        resources :invites, only: %i[create update]
      end
      resources :hobbies, only: %i[new create], as: 'account_hobbies'
    end

    scope module: :conversations do
      resources :conversations, shallow: true, except: %i[index show new create edit update destroy] do
        resources :messages, only: %i[create edit update destroy]
      end
    end

    shallow do
      resources :accounts do
        resources :friendships, only: %i[index destroy]
        resources :groups
      end
      resources :invites, except: %i[index show new create edit destroy] do
        resources :friendships, except: %i[index new show update destroy edit]
      end
      resources :posts do
        resources :comments, except: %i[show index]
      end
      resources :contents, except: %i[index show new create edit update destroy] do
        resources :comments, except: %i[show index]
      end
    end

    scope module: :groups do
      resources :groups, shallow: true, except: %i[index show new create edit update destroy] do
        resources :hobbies, except: %i[show index]
        resources :contents, except: %i[index]
      end
    end

    get 'account/:id/your_groups', to: 'groups#your_groups', as: 'your_groups'
    get 'account/:id/participation_groups', to: 'groups#participation_groups', as: 'participation_groups'
  end
end
# rubocop:enable Metrics/BlockLength

app/models/content.rb
# frozen_string_literal: true

class Content < ApplicationRecord
  validates :body, presence: true, length: { minimum: 2 }
  has_many_attached :images

  belongs_to :group
  belongs_to :account

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :order_desc, -> { order_desc }, class_name: 'Comment',
                                           inverse_of: :comment,
                                           dependent: :destroy
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  VALID_VISIBILITY = %w[everybody participants].freeze

  validates :name_group, presence: true, length: { within: 2..50 }
  validates :description, presence: true, length: { minimum: 2 }

  validates :visibility, inclusion: { in: VALID_VISIBILITY }

  has_many :group_participants, dependent: :destroy
  has_many :accounts, through: :group_participants

  has_many :group_hobbies, dependent: :destroy
  has_many :hobbies, through: :group_hobbies
  accepts_nested_attributes_for :hobbies, allow_destroy: true, update_only: true

  belongs_to :group_creator, class_name: 'Account', optional: true
  has_many :contents, dependent: :destroy

  has_one_attached :group_image
end

app/controllers/groups/contents_controller.rb
# frozen_string_literal: true

module Groups
  class ContentsController < ApplicationController
    before_action :authenticate_user!
    before_action :define_content!, except: %i[new create]
    before_action :define_group!, only: %i[new create]
    before_action :define_account!

    def show
      @group = @content.group
      @pagy_comment, @comments = pagy @content.comments.order_desc, items: 4, page_param: :pagy_comment
      @comments = @comments.decorate
    end

    def new
      @content = @group.contents.build
    end

    def edit; end

    def create
      @content = @group.contents.build content_params
      @content.account = @account
      if @content.save
        redirect_to content_path(@content),
                    success: I18n.t('flash.new', model: i18n_model_name(@content).downcase)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      return unless @account == @content.account

      if @content.update content_params
        redirect_to content_path(@content),
                    success: I18n.t('flash.update', model: i18n_model_name(@content).downcase)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      return unless @content.destroy

      redirect_to group_path(@group),
                  success: I18n.t('flash.destroy', model: i18n_model_name(@content).downcase)
    end

    private

    def define_content!
      @content = Content.find(params[:id]).decorate
    end

    def define_group!
      @group = Group.find params[:group_id]
    end

    def define_account!
      @account = Account.find_by user_id: current_user.id
    end

    def content_params
      params.require(:content).permit(:body, images: [])
    end
  end
end

app/controllers/groups/hobbies_controller.rb
# frozen_string_literal: true

module Groups
  class HobbiesController < ApplicationController
    before_action :authenticate_user!
    before_action :define_group!
    include HobbyAdd

    def new
      @hobby = Hobby.new
    end

    def create
      @hobby = Hobby.new_hobby hobby_params
      if @hobby.save
        hobby_add(@group, @hobby)
        return redirect_to group_path(@group),
                           success: I18n.t('flash.new', model: i18n_model_name(@hobby).downcase)
      end

      redirect_to group_path(@group),
                  danger: @hobby.errors.full_messages.each(&:capitalize).join(' ').to_s
    end

    private

    def define_group!
      @group = Group.find params[:group_id]
    end

    def hobby_params
      params.require(:hobby).permit(:hobby_name)
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :define_account!, except: %i[edit update destroy]
  before_action :define_group!, except: %i[index new create]

  def index
    @pagy, @all_groups = pagy Group.order(:name_group), items: 5
    @all_groups = @all_groups.decorate
  end

  def your_groups
    @pagy, @created_groups = pagy Group.where(group_creator: @account).order(:name_group), items: 5
    @created_groups = @created_groups.decorate
  end

  def participation_groups
    # @pagy, @participation_groups = pagy @account.groups.where.not(group_creator_id: @account.id), items: 5
    # @participation_groups = @participation_groups.decorate
  end

  def show
    @hobby = Hobby.new
    @pagy, @contents = pagy @group.contents.order(created_at: :desc), items: 5
    @contents = @contents.decorate
    @participants = @group.accounts
  end

  def new
    @group = @account.groups.build
    3.times { @group.hobbies.build }
  end

  def edit; end

  def create
    @group = @account.groups.build group_params
    if @group.save
      redirect_to group_path(@group),
                  success: I18n.t('flash.new', model: i18n_model_name(@group).downcase)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    return unless @group.group_creator == current_user.account

    if @group.update(group_params)
      redirect_to  group_path(@group),
                   success: I18n.t('flash.update', model: i18n_model_name(@group).downcase)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    return unless @group.group_creator == current_user.account
    return unless @group.destroy

    redirect_to account_groups_path(current_user.account),
                success: I18n.t('flash.destroy', model: i18n_model_name(@group).downcase)
  end

  private

  def define_account!
    @account = Account.find_by user_id: current_user.id
  end

  def define_group!
    @group = Group.find(params[:id]).decorate
  end

  def become_group_participant
    @account = Account.find_by user_id: current_user.id
    @group.accounts << @account unless @group.accounts.exists?(@account.id)
  end
  helper_method :become_group_participant

  def group_params
    params.require(:group).permit(:name_group, :description, :visibility,
                                  hobbies_attributes: %i[id hobby_name _destroy], 
                                  :group_image)
  end
end

app/helpers/contents_helper.rb
# frozen_string_literal: true

module ContentsHelper
  def anchor(content)
    dom_id(content.comments.order_desc.first)
  end
end

app/helpers/group_helper.rb
# frozen_string_literal: true

module GroupHelper
  def group_page_name(page_name = '')
    render partial: 'navigation', locals: { page_name: page_name }
  end

  def link_nav(title, url, options = {})
    page_name = options.delete :page_name
    css_text = page_name == title ? 'btn btn-dark my-2 btn-sm' : 'btn btn-outline-dark my-2 btn-sm'
    options[:class] = if options[:class]
                        "#{options[:class]} #{css_text}"
                      else
                        css_text
                      end

    link_to title, url, options
  end
end

app/views/groups/contents/_content.html.erb
<article class="article">
  <p class="infopost">
    <%= attribute_model(content, :account) %>
    <%= link_to content.account.decorate.capitalize_name, account_path(content.account) %>
    &nbsp;&bull;&nbsp;
    <span class="me-4 date">
      <time datetime="<%= content.created_at %>">
        <%= content.formatted_created_at %>
      </time>
    <span>
    <span class='mx-5'>
      <% if content.comments.try(:any?) %>
        <%= link_to(post_path(content, anchor: anchor(content)), class: "com") do %>
          <%= i18n_model_name(Comment.new, count: 2) %>
          <i class="bi bi-chat"><span><%= content.comments.count %></span></i>
        <% end %>
      <% end %>
    </span>
  </p>
  <div class="clr"></div>
  <div class="post_content">
    <p>
      <%= truncate strip_tags(content.body), length: 300, omission: '... (continued)' %>
    </p>
    <p class="spec" >
      <%= link_to sanitize(t('link.show_post')), content_path(content), class: "rm" %>
    </p>
  </div>
  <div class="clr"></div>
</article>

app/views/groups/contents/_empty_state.html.erb
<article class='article'>
  <p><%= t('page.content.blank') %></p>
  <%= turbo_frame_tag dom_id(Content.new) do %>
    <%= link_to t('link.add_new_plural', model: attribute_model(Content.new, :body).downcase), 
        new_group_content_path(@group), class: "btn btn-outline-dark btn-sm mb-4" %>
  <% end %>
</article>

app/views/groups/contents/_form.html.erb
<%= simple_form_for model, method: method do |f| %>
	<%= f.input :body, input_html: {rows: 5} %>
	<%= f.button :submit, f.object.new_record? ? t('submit.create', model: i18n_model_name(f.object).downcase) 
                                              	: t('submit.edit', model: i18n_model_name(f.object).downcase), 
                                              	class: "btn btn-outline-dark my-2 btn-sm" %>	
	<%= render partial: 'shared/cancel_button', locals: { path: path } if f.object.persisted? %>	
<% end %>

app/views/groups/contents/edit.html.erb
<%= turbo_frame_tag dom_id(@content) do %>
  <article class='article'> 
    <h4 class='mt-4 mb-2'><%= t('page.edit', model: i18n_model_name(@content)) %></h4>
    <%= render partial: 'form', locals: { model: @content, method: :put, path: content_path(@content) } %>
  </article>
<% end %>

app/views/groups/contents/new.html.erb
<%= turbo_frame_tag dom_id(@content) do %>
  <article class="article">
    <h4 class='mt-4 mb-2'><%= t('page.new', model: i18n_model_name(@content).downcase) %></h4>
    
    <%= render partial: 'shared/go_back_button', locals: { path: group_path(@group) } %>
    <%= render partial: 'form',  locals: { model: [@group, @content], method: :post } %>
  </article>
<% end %>

app/views/groups/contents/show.html.erb
<% provide :page_title, i18n_model_name(@content)%>
<% currently_at %>

<article class='article'>
  <%= turbo_frame_tag dom_id(@content) do %>
    <%= render partial: 'shared/go_back_button', locals: { path: group_path(@group) } %>
    <p class="infopost">
      <%= attribute_model(@content, :account) %>
      <%= link_to @content.account.decorate.capitalize_name, account_path(@content.account) %>
      &nbsp;&bull;&nbsp;
      <time datetime="<%= @content.formatted_created_at %>">
        <%= @content.formatted_created_at %>
      </time>
    </p>
    <p><%= strip_tags @content.body %></p>
    <p>
      <strong>
        <% if @comments.try(:any?) %>
          <%= link_to(content_path(@content,  anchor: anchor(@content))) do %>
            <%= i18n_model_name(Comment.new, count: 2) %>(<%= @content.comments.count %>)
          <% end %>
        <% end %>
      </strong>
    </p>
  <% end %>
</artcile>

<div class="btn-group my-4" role="group">
  <%= link_to t('link.edit', model: i18n_model_name(@content).downcase), 
      edit_content_path(@content), class: "btn btn-outline-dark btn-sm me-2" if @content.account == @account %>
  <% if @content.account == @account || @group.group_creator == @account %>
    <%= button_to t('submit.delete', model: i18n_model_name(@content).downcase), content_path(@content), 
        method: :delete, class: "btn btn-outline-dark btn-sm me-2", 
        :onclick => "return confirm('Are you sure?')", :remote => true %>
  <% end %>
</div>

<%= render partial: "comments/form", locals: { model: [@content, Comment.new], method: :post } %>

<section class='my-3'>
  <% if @comments.try(:any?) %>
    <h3 class='md-4'><%= i18n_model_name(Comment.new, count: 2) %></h3>
    <div class="clr"></div>
      <%= render partial: 'comments/comment', collection: @comments %>
    <div class='my-2'>
      <%== pagination(@pagy_comment) %>
    </div>
  <% end %>
</section>